apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage
  namespace: velero-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2