apiVersion: v1
kind: Service
metadata:
  name: backend-service-lb
  namespace: tictactoe
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP