apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  # Use EKS optimized AMI
  amiFamily: AL2
  
  # Use the instance profile we created
  instanceProfile: "KarpenterNodeInstanceProfile"
  
  # Security groups (use your cluster's security groups)
  securityGroupSelector:
    karpenter.sh/discovery: "preprod_eks_cluster"
  
  # Subnets (use your cluster's private subnets)
  subnetSelector:
    karpenter.sh/discovery: "preprod_eks_cluster"
        
  # User data for EKS bootstrap
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    /etc/eks/bootstrap.sh preprod_eks_cluster

    --BOUNDARY--