apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  # Reference the AWSNodeTemplate we created
  providerRef:
    name: default
  
  # Instance requirements  
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.small", "t3.medium", "t3.large", "c5.large", "c5.xlarge"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  
  # Set limits to control costs
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  
  # Automatic consolidation for cost savings
  consolidation:
    enabled: true
  
  # Node properties
  labels:
    intent: apps